import type { Weapon, WeaponId } from "./types";

export const WEAPONS: Record<WeaponId, Weapon> = {
  knife: {
    id: "knife",
    name: "Tactical Knife",
    shortName: "KNIFE",
    damage: 38,
    range: 1.8,
    fireRate: 5,
    ammoCost: 0,
    color: "#b8f7ff",
  },
  m9: {
    id: "m9",
    name: "M9",
    shortName: "M9",
    damage: 28,
    range: 16,
    fireRate: 3.4,
    ammoCost: 1,
    color: "#7be7ff",
  },
  glock29: {
    id: "glock29",
    name: "Glock 29",
    shortName: "G29",
    damage: 34,
    range: 14,
    fireRate: 3,
    ammoCost: 1,
    color: "#74ffc9",
  },
  scarlm: {
    id: "scarlm",
    name: "SCAR-LM",
    shortName: "SCAR",
    damage: 22,
    range: 22,
    fireRate: 8,
    ammoCost: 1,
    color: "#ffdd74",
  },
  m134: {
    id: "m134",
    name: "9M 134",
    shortName: "M134",
    damage: 18,
    range: 18,
    fireRate: 14,
    ammoCost: 1,
    color: "#ff79d8",
  },
  m667: {
    id: "m667",
    name: "M667",
    shortName: "M667",
    damage: 62,
    range: 9,
    fireRate: 1.4,
    ammoCost: 2,
    color: "#ff8f5f",
  },
  barrett: {
    id: "barrett",
    name: "Barrett M82A1",
    shortName: "M82",
    damage: 120,
    range: 35,
    fireRate: 0.8,
    ammoCost: 3,
    color: "#f5f7ff",
  },
};

export const LOOT_WEAPONS: WeaponId[] = [
  "m9",
  "glock29",
  "scarlm",
  "m134",
  "m667",
  "barrett",
];
